package main

import (
	"context"
	"flag"
	"fmt"
	"log"
	"os"
	"time"

	"github.com/Manny-14/LAD/internal/summarizer"
)

func main() {
	cfg := parseFlags()

	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()

	if cfg.DryRun {
		prompt, err := summarizer.PreparePrompt(cfg.SummaryConfig)
		if err != nil {
			log.Fatal(err)
		}
		fmt.Println(prompt)
		return
	}

	apiKey := cfg.APIKey
	if apiKey == "" {
		apiKey = os.Getenv("GEMINI_API_KEY")
	}
	if apiKey == "" {
		apiKey = os.Getenv("GOOGLE_API_KEY")
	}
	if apiKey == "" {
		log.Fatal("Gemini API key not provided. Set GEMINI_API_KEY or use --api-key flag, or run with --dry-run")
	}

	client, err := summarizer.NewGeminiClient(ctx, apiKey, cfg.ModelID)
	if err != nil {
		log.Fatal(err)
	}
	defer func() {
		if err := client.Close(); err != nil {
			log.Printf("warning: closing Gemini client: %v", err)
		}
	}()

	summary, err := summarizer.GenerateSummary(ctx, cfg.SummaryConfig, client)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(summary)
}

type cliConfig struct {
	summarizer.SummaryConfig
	APIKey  string
	ModelID string
	DryRun  bool
}

func parseFlags() cliConfig {
	var cfg cliConfig

	flag.StringVar(&cfg.PredictionsPath, "predictions", "outputs/isolation_forest_predictions.csv", "Path to the predictions CSV generated by the inference step")
	flag.StringVar(&cfg.LogPath, "logs", "data/HDFS.log", "Path to the raw log file used during preprocessing")
	flag.StringVar(&cfg.OutputPath, "output", "outputs/anomaly_summary.txt", "Where to write the LLM summary (defaults to outputs/anomaly_summary.txt)")
	flag.IntVar(&cfg.TopN, "top", 20, "Number of most severe anomalies to include in the prompt (<=0 means all)")
	flag.StringVar(&cfg.SystemPrompt, "prompt", "", "Optional custom system prompt prefix for the LLM request")
	flag.IntVar(&cfg.MaxLinesPerBlock, "max-lines", 100, "Maximum log lines to include per block (0 means unlimited)")
	flag.StringVar(&cfg.APIKey, "api-key", "", "Gemini API key (falls back to GEMINI_API_KEY/GOOGLE_API_KEY env vars)")
	flag.StringVar(&cfg.ModelID, "model", summarizer.DefaultModel, "Gemini model id to use (e.g. gemini-1.5-flash)")
	flag.BoolVar(&cfg.DryRun, "dry-run", false, "Skip the LLM call and output the assembled prompt instead")

	flag.Parse()

	if cfg.DryRun {
		cfg.OutputPath = ""
	}

	return cfg
}
